version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.13
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go test -v ./...

  deploy:
    docker:
      - image: circleci/golang:1.13
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go get -u github.com/mitchellh/gox
      - run: go get -u github.com/tcnksm/ghr
      - run:
          name: cross compile
          command: |
            gox -os="linux darwin windows" -arch="amd64" -output="dist/terraform-provider-checkly_${CIRCLE_TAG}_{{.OS}}_{{.Arch}}"
            cd dist/ && gzip *
      - add_ssh_keys
      - run:
          name: create release
          command: |
            if [ "$CIRCLE_TAG" ]; then
              ghr -t $GITHUB_TOKEN -u bitfield -r terraform-provider-checkly --replace $CIRCLE_TAG dist/
            else
              echo "no tagged version to deploy"
            fi

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
            tags:
              only: /^v.*/
