name: Go

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          stable: false
          go-version: 1.16.0-beta1

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          path: ./src/github.com/thiagonache/go-history

      - name: Get dependencies
        run: |
          go get -v -d ./...
          if [ -f Gopkg.toml ]; then
              curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
              dep ensure
          fi
        working-directory: ./src/github.com/thiagonache/go-history

      - name: Build
        run: go build -v ./...
        working-directory: ./src/github.com/thiagonache/go-history

      - name: Test
        run: go test -v ./...
        working-directory: ./src/github.com/thiagonache/go-history
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          stable: false
          go-version: 1.16.0-beta1

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          path: ./src/github.com/thiagonache/go-history

      - name: Get dependencies
        run: |
          go get -v -d ./...
          if [ -f Gopkg.toml ]; then
              curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
              dep ensure
          fi
        working-directory: ./src/github.com/thiagonache/go-history

      - name: Format
        run: |
          if [[ $(gofmt -d . | wc -c) -ne 0 ]]; then
            gofmt -d .
            exit 1
          fi
        working-directory: ./src/github.com/thiagonache/go-history

      - name: Vet
        run: go vet
        working-directory: ./src/github.com/thiagonache/go-history
